-- ## Lesson 6 tasks:

-- 1) Select Payments with “MONTHLY” type;
SELECT PAYMENT .* FROM PAYMENT LEFT JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID WHERE NAME = 'MONTHLY';

-- 2) Select all marks by Art
SELECT MARK.* FROM MARK LEFT JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID WHERE NAME = 'Art';

-- 3) Select all students who have “WEEKLY” payments;
SELECT STUDENT.* FROM STUDENT LEFT JOIN PAYMENT ON STUDENT.ID = PAYMENT.STUDENT_ID LEFT JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME = 'WEEKLY';

-- 4) Select all students who has marks by Math.
SELECT STUDENT.* FROM STUDENT LEFT JOIN MARK ON STUDENT.ID = MARK.STUDENT_ID LEFT JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID WHERE SUBJECT.NAME = 'Math';


