INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'John', '2013-01-03', 1);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Chris', '2013-01-03', 1);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Carl', '2013-01-03', 1);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Oliver', '2013-01-03', 2);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'James', '2013-01-03', 2);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Lucas', '2013-01-03', 2);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Henry', '2013-01-03', 2);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Jacob', '2013-01-03', 3);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Logan', '2013-01-03', 3);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Kate', '2013-01-03', 4);
INSERT INTO STUDENT ( NAME, BIRTHDAY, GROUPNUMBER) values ( 'Yura', '2013-01-03', 5);

INSERT INTO SUBJECT ( name, grade)  values ( 'Art', 1);
INSERT INTO SUBJECT ( name, grade) values ( 'Geography', 2 );
INSERT INTO SUBJECT ( name, grade)  values ( 'PE', 3);
INSERT INTO SUBJECT ( name, grade) values ( 'Science', 4 );
INSERT INTO SUBJECT ( name, grade)  values ( 'Math', 5);
INSERT INTO SUBJECT ( name, grade) values ( 'History', 5 );

INSERT INTO PAYMENTTYPE ( NAME) values ( 'DAILY');
INSERT INTO PAYMENTTYPE ( NAME) values (  'WEEKLY' );
INSERT INTO PAYMENTTYPE ( NAME) values (  'MONTHLY' );

INSERT INTO PAYMENT ( TYPE_ID, STUDENT_ID, AMOUNT, PAYMENT_DATE) VALUES (2, 1, 50, '2013-01-03');
INSERT INTO PAYMENT ( TYPE_ID, STUDENT_ID, AMOUNT, PAYMENT_DATE) VALUES (3, 4, 50, '2013-01-03');
INSERT INTO PAYMENT ( TYPE_ID, STUDENT_ID, AMOUNT, PAYMENT_DATE) VALUES (2, 7,  50, '2013-01-03');
INSERT INTO PAYMENT ( TYPE_ID, STUDENT_ID, AMOUNT, PAYMENT_DATE) VALUES (1,5, 50, '2013-01-03');


insert into MARK (STUDENT_ID, SUBJECT_ID, MARK) values ( 2, 1, 8);
insert into MARK (STUDENT_ID, SUBJECT_ID, MARK) values ( 4, 6, 5);
insert into MARK (STUDENT_ID, SUBJECT_ID, MARK) values ( 5, 2, 9);
insert into MARK (STUDENT_ID, SUBJECT_ID, MARK) values ( 8, 5, 4);
insert into MARK (STUDENT_ID, SUBJECT_ID, MARK) values ( 9, 3, 9);
insert into MARK (STUDENT_ID, SUBJECT_ID, MARK) values ( 1, 4, 6);
insert into MARK (STUDENT_ID, SUBJECT_ID, MARK) values ( 3, 6, 2);